site_name: OSCAR Documentation
repo_url: https://github.com/grycap/oscar
nav:
- Introduction: 
   - index.md
   - Multitenancy: multitenancy.md
  
- Deployment:
  - local-testing.md
  - deploy-im-dashboard.md
  - deploy-ec3.md
  - deploy-helm.md
  - deploy-k3s-ansible.md
  
- Service Definition:
  - oscar-service.md 
  - fdl.md
  - fdl-composer.md

- Interfaces:
  - oscar-cli.md
  - usage-ui.md  
  - api.md

- Service Execution: 
  - invoking.md
  - invoking-sync.md
  - invoking-async.md
  - exposed-services.md

- Integrations:
  - integration-egi.md
  - integration-scone.md
  - integration-interlink.md
  - integration-compss.md

- Tutorials: 
  - training.md
  - faq.md

- Advanced Features:   
  - MinIO bucket replication: minio-bucket-replication.md
  - Mount: mount.md

- Development:
  - Documentation: devel-docs.md
- license.md
- about.md

theme:
  favicon: images/logo.png
  logo: images/logo.png
  name: material
  palette:
    primary: teal
  features:
    - instant
    - toc.integrate
    - content.code.copy

plugins:
- search
- render_swagger

copyright: "&copy; GRyCAP - I3M - Universitat Politècnica de València, Spain."