site_name: OSCAR Documentation
repo_url: https://github.com/grycap/oscar
nav:
- Introduction: index.md
- Deployment:
  - local-testing.md
  - deploy-im-dashboard.md
  - deploy-ec3.md
  - deploy-helm.md
  - deploy-k3s-ansible.md
- Service Definition:
  - Functions Definition Language (FDL): fdl.md
  - FDL Composer: fdl-composer.md
- Service Execution: 
  - invoking.md
  - Exposed services: expose_services.md
- Usage:
  - usage-ui.md
  - oscar-cli.md
  - api.md
- training.md

- Advanced Features:   
  - Multitenancy: multitenancy.md
  - MinIO bucket replication: minio-bucket-replication.md

- Third party integrations:
  - Integration with EGI: egi-integration.md
  - OIDC Authorization: oidc-auth.md
  - Integration with SCONE: sgx-integration.md
  - Interlink: interlink_integration.md

- Frequently Asked Questions (FAQ): faq.md
- Development:
  - Documentation: devel-docs.md
- license.md
- about.md
theme:
  favicon: images/logo.png
  logo: images/logo.png
  name: material
  palette:
    primary: teal
  features:
    - instant
    - toc.integrate
    - content.code.copy
plugins:
- search
- render_swagger
copyright: "&copy; 2022, GRyCAP - i3M - Universitat Politècnica de València, Spain."