functions:
  oscar:
  - oscar:
     name: simple-test42
     memory: 256Mi
     cpu: '1.0'
     image: ubuntu
     script: script.sh
     allowed_users: []
     log_level: CRITICAL		
     input:
     - storage_provider: minio.default
       path: simple-2/input
     output:
     - storage_provider: minio.default
       path: simple-2/output
